version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always

  myprogram:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myprogram
    depends_on:
      - jenkins
    environment:
      - JENKINS_URL=http://jenkins:8080/
    restart: always

volumes:
  jenkins_home:
