version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=admin
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - jenkins
    environment:
      - JENKINS_URL=http://jenkins:8080/
    restart: always

volumes:
  jenkins_home:
